### PR TITLE
Update `.ruby-style.yml` file

### PR DESCRIPTION
**Pull request by filipebarros**

### CODE REVIEW

**Comment by filipebarros** [comment]
@damien updated it for the latest version. Should we look for a way to __enforce__ people to update the version of the project they work on? One way to do this is to actually create a gem out of this repo and then use the style guide gem in the ruby projects and `inherit_gem` http://rubocop.readthedocs.io/en/latest/configuration/#inheriting-configuration-from-a-dependency-gem

**Comment by damien** [comment]
@filipebarros great questions!

`inherit_gem` is definitely something I've been wanting to get around to implementing, though making usage of that ergonomic may take some figuring out.

To your second point, I'm not sure I want to _enforce_ usage of this style guide, at least not without buy-in from the teams who are going to be using it. I find that it's usually more trouble than it's worth to force tooling onto teams that don't want it. At the moment this stye guide is more an informal codification of how a few teams in the US have been writing ruby.

If you have things you'd like to change about this repo or style guide, feel free to open up GH issues or PRs, I'm always happy to see more people taking an interest in tooling and code quality in teams I work with!

**Comment by filipebarros** [comment]
When I said _enforcing_, I actually meant a start point. I still think that it's up for each team to actually adopt the code styles they want. I just think that maybe we can start from somewhere and then, everyone can add their own customisations.

**Comment by damien** [comment]
Seems we're on the same page! Happy to discuss those points and assist making that process ergonomic, though all that's probably outside the context of this PR. :)

Looks like CircleCI has made changes to how they look up project configs. I'll see if I can sort that out today—once that's fixed you should be able to rebase and see this branch go green.

**Comment by filipebarros** [comment]
@damien should this be merged or should I close it?

**Pull request merged**
